language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


before_script:
    npm install hexo-cli -g

script:
  - hexo generate

after_script:
  - rm -rf .git/
  - git init
  - git config user.name "Wind"
  - git config user.email "mofeng64@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/StreetWind/StreetWind.github.io.git
